version: "3.9"

services:
  taoli-tools-container:
    image: ghcr.io/aliez-ren/taoli-tools-container:latest
    volumes:
      - taoli-tools-data:/home/taoli/data
      - tailscale-state:/var/lib/tailscale
      - /mnt:/home/taoli/cert
    networks:
      - public
      - private
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 0s
      update_config:
        order: start-first
        parallelism: 1
        delay: 5s
      rollback_config:
        order: stop-first

  taoli-tools-signer:
    image: ghcr.io/aliez-ren/taoli-tools-signer:latest
    secrets:
      - KEYCHAIN
      - CERT.pem
      - KEY.pem
    networks:
      - private
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 0s
      update_config:
        order: start-first
        parallelism: 1
        delay: 5s
      rollback_config:
        order: stop-first

networks:
  public:
    driver: overlay
    attachable: true
  private:
    driver: overlay
    attachable: true
    internal: true

volumes:
  taoli-tools-data:
    driver: local
  tailscale-state:
    driver: local

secrets:
  KEYCHAIN:
    file: keychain.toml
  CERT.pem:
    file: CERT.pem
  KEY.pem:
    file: KEY.pem
