version: "3.9"

services:
  container:
    image: ghcr.io/aliez-ren/taoli-tools-container:latest
    volumes:
      - data:/home/taoli/data
      - tailscale:/home/taoli/.local/share/tailscale/
      - /mnt:/home/taoli/cert
    networks:
      - public
      - private
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 0s
      update_config:
        order: start-first
        parallelism: 1
        delay: 5s
      rollback_config:
        order: stop-first

  signer:
    image: ghcr.io/aliez-ren/taoli-tools-signer:latest
    secrets:
      - KEYCHAIN
      - CERT.pem
      - KEY.pem
    networks:
      - private
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 0s
      update_config:
        order: start-first
        parallelism: 1
        delay: 5s
      rollback_config:
        order: stop-first

networks:
  public:
    driver: overlay
    attachable: true
  private:
    driver: overlay
    attachable: true
    internal: true

volumes:
  data:
    driver: local
  tailscale:
    driver: local

secrets:
  KEYCHAIN:
    file: keychain.toml
  CERT.pem:
    file: CERT.pem
  KEY.pem:
    file: KEY.pem
