services:
  gui:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RUSTDESK_ID_SERVER: hbbs
      RUSTDESK_RELAY_SERVER: hbbr:21117
      RUSTDESK_API_SERVER: http://hbbs:21114
    depends_on:
      - hbbs
      - hbbr
    ports:
      - "21112:21112"
    shm_size: 2g
    volumes:
      - gui-home:/home/app

  hbbs:
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    environment:
      RUSTDESK_KEY: test
    ports:
      - "21114:21114"
      - "21115:21115"
      - "21116:21116"
    restart: unless-stopped
    volumes:
      - server-data:/root

  hbbr:
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    environment:
      RUSTDESK_KEY: test
    ports:
      - "21117:21117"
      - "21118:21118"
    restart: unless-stopped
    volumes:
      - server-data:/root

volumes:
  gui-home:
  server-data:
